// Package docs GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import (
	"bytes"
	"encoding/json"
	"strings"
	"text/template"

	"github.com/swaggo/swag"
)

var doc = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "FengYu",
            "url": "https://hyy-yu.space"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/v1/config/add": {
            "post": {
                "tags": [
                    "配置管理"
                ],
                "summary": "添加配置",
                "parameters": [
                    {
                        "description": "data",
                        "name": "params",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.AddConfig"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "data=ok",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.JsonResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/v1/config/copy": {
            "post": {
                "tags": [
                    "配置管理"
                ],
                "summary": "副本配置",
                "parameters": [
                    {
                        "description": "data",
                        "name": "params",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.ConfigCopy"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "data=ok",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.JsonResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/v1/config/del": {
            "post": {
                "tags": [
                    "配置管理"
                ],
                "summary": "删除配置",
                "parameters": [
                    {
                        "description": "ConfigId",
                        "name": "config_id",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "integer"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "data=ok",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.JsonResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/v1/config/edit": {
            "post": {
                "tags": [
                    "配置管理"
                ],
                "summary": "编辑配置",
                "parameters": [
                    {
                        "description": "data",
                        "name": "params",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.EditConfig"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "data=ok",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.JsonResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/v1/config/history": {
            "get": {
                "tags": [
                    "配置管理"
                ],
                "summary": "配置历史",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "配置ID",
                        "name": "config_id",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "data",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.JsonResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/model.ConfigHistoryList"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/v1/config/info": {
            "get": {
                "tags": [
                    "配置管理"
                ],
                "summary": "配置详情",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "配置ID",
                        "name": "config_id",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "data",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.JsonResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/model.ConfigInfo"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/v1/config/rollback": {
            "post": {
                "tags": [
                    "配置管理"
                ],
                "summary": "回滚配置",
                "parameters": [
                    {
                        "description": "data",
                        "name": "params",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.RollbackConfig"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "data=ok",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.JsonResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/v1/config/tree": {
            "get": {
                "tags": [
                    "配置管理"
                ],
                "summary": "配置树",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "配置ID",
                        "name": "project_id",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "data",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.JsonResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/model.ProjectTree"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/v1/namespace/add": {
            "post": {
                "tags": [
                    "命名空间管理"
                ],
                "summary": "添加命名空间",
                "parameters": [
                    {
                        "description": "data",
                        "name": "params",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.AddNamespace"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "data=ok",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.JsonResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/v1/namespace/del": {
            "post": {
                "tags": [
                    "命名空间管理"
                ],
                "summary": "删除命名空间",
                "parameters": [
                    {
                        "description": "NamespaceId",
                        "name": "namespace_id",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "integer"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "data=ok",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.JsonResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/v1/namespace/edit": {
            "post": {
                "tags": [
                    "命名空间管理"
                ],
                "summary": "编辑命名空间",
                "parameters": [
                    {
                        "description": "data",
                        "name": "params",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.EditNamespace"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "data=ok",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.JsonResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/v1/namespace/list": {
            "get": {
                "tags": [
                    "命名空间管理"
                ],
                "summary": "命名空间列表",
                "parameters": [
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "页号",
                        "name": "page_index",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 10,
                        "description": "页长",
                        "name": "page_size",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "排序字段",
                        "name": "sort",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "命名空间ID",
                        "name": "namespace_id",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "命名空间名称",
                        "name": "namespace_name",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "data",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.JsonResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "allOf": [
                                                {
                                                    "$ref": "#/definitions/page.Page"
                                                },
                                                {
                                                    "type": "object",
                                                    "properties": {
                                                        "List": {
                                                            "$ref": "#/definitions/model.NamespaceList"
                                                        }
                                                    }
                                                }
                                            ]
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/v1/project/add": {
            "post": {
                "tags": [
                    "项目管理"
                ],
                "summary": "添加项目",
                "parameters": [
                    {
                        "description": "data",
                        "name": "params",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.AddProject"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "data=ok",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.JsonResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/v1/project/del": {
            "post": {
                "tags": [
                    "项目管理"
                ],
                "summary": "删除项目",
                "parameters": [
                    {
                        "description": "ProjectId",
                        "name": "project_id",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "integer"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "data=ok",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.JsonResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/v1/project/edit": {
            "post": {
                "tags": [
                    "项目管理"
                ],
                "summary": "编辑项目",
                "parameters": [
                    {
                        "description": "data",
                        "name": "params",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.EditProject"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "data=ok",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.JsonResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/v1/project/list": {
            "get": {
                "tags": [
                    "项目管理"
                ],
                "summary": "项目列表",
                "parameters": [
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "页号",
                        "name": "page_index",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 10,
                        "description": "页长",
                        "name": "page_size",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "排序字段",
                        "name": "sort",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "项目ID",
                        "name": "project_id",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "项目名称",
                        "name": "project_name",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "data",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.JsonResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "allOf": [
                                                {
                                                    "$ref": "#/definitions/page.Page"
                                                },
                                                {
                                                    "type": "object",
                                                    "properties": {
                                                        "List": {
                                                            "$ref": "#/definitions/model.ProjectList"
                                                        }
                                                    }
                                                }
                                            ]
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/v1/project_group/add": {
            "post": {
                "tags": [
                    "项目组管理"
                ],
                "summary": "添加项目组",
                "parameters": [
                    {
                        "description": "data",
                        "name": "params",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.AddProjectGroup"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "data=ok",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.JsonResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/v1/project_group/del": {
            "post": {
                "tags": [
                    "项目组管理"
                ],
                "summary": "删除项目组",
                "parameters": [
                    {
                        "description": "GroupId",
                        "name": "group_id",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "integer"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "data=ok",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.JsonResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/v1/project_group/edit": {
            "post": {
                "tags": [
                    "项目组管理"
                ],
                "summary": "编辑项目组",
                "parameters": [
                    {
                        "description": "data",
                        "name": "params",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.EditProjectGroup"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "data=ok",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.JsonResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/v1/project_group/list": {
            "get": {
                "tags": [
                    "项目组管理"
                ],
                "summary": "项目组列表",
                "parameters": [
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "页号",
                        "name": "page_index",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 10,
                        "description": "页长",
                        "name": "page_size",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "排序字段",
                        "name": "sort",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "项目组ID",
                        "name": "project_group_id",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "项目组名称",
                        "name": "project_group_name",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "data",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.JsonResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "allOf": [
                                                {
                                                    "$ref": "#/definitions/page.Page"
                                                },
                                                {
                                                    "type": "object",
                                                    "properties": {
                                                        "List": {
                                                            "$ref": "#/definitions/model.ProjectGroupList"
                                                        }
                                                    }
                                                }
                                            ]
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/v1/publish/add": {
            "post": {
                "tags": [
                    "发布管理"
                ],
                "summary": "添加发布",
                "parameters": [
                    {
                        "description": "data",
                        "name": "params",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.AddPublish"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "data=ok",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.JsonResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/v1/publish/list": {
            "get": {
                "tags": [
                    "发布管理"
                ],
                "summary": "发布列表",
                "parameters": [
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "页号",
                        "name": "page_index",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 10,
                        "description": "页长",
                        "name": "page_size",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "排序字段",
                        "name": "sort",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "项目ID",
                        "name": "project_id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "data",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.JsonResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "allOf": [
                                                {
                                                    "$ref": "#/definitions/page.Page"
                                                },
                                                {
                                                    "type": "object",
                                                    "properties": {
                                                        "List": {
                                                            "$ref": "#/definitions/model.PublishConfigList"
                                                        }
                                                    }
                                                }
                                            ]
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/v1/publish/rollback": {
            "post": {
                "tags": [
                    "发布管理"
                ],
                "summary": "添加发布",
                "parameters": [
                    {
                        "description": "data",
                        "name": "params",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.RollbackPublish"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "data=ok",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.JsonResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/v1/staff/add": {
            "post": {
                "tags": [
                    "员工管理"
                ],
                "summary": "添加员工",
                "parameters": [
                    {
                        "description": "data",
                        "name": "params",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.AddStaff"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "data=ok",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.JsonResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/v1/staff/del": {
            "post": {
                "tags": [
                    "员工管理"
                ],
                "summary": "删除员工",
                "parameters": [
                    {
                        "description": "StaffId",
                        "name": "staff_id",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "integer"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "data=ok",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.JsonResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/v1/staff/edit": {
            "post": {
                "tags": [
                    "员工管理"
                ],
                "summary": "编辑员工",
                "parameters": [
                    {
                        "description": "data",
                        "name": "params",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.EditStaff"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "data=ok",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.JsonResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/v1/staff/grant": {
            "post": {
                "tags": [
                    "员工管理"
                ],
                "summary": "赋权员工",
                "parameters": [
                    {
                        "description": "data",
                        "name": "params",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.GrantStaff"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "data=ok",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.JsonResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/v1/staff/list": {
            "get": {
                "tags": [
                    "员工管理"
                ],
                "summary": "员工列表",
                "parameters": [
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "页号",
                        "name": "page_index",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 10,
                        "description": "页长",
                        "name": "page_size",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "排序字段",
                        "name": "sort",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "员工ID",
                        "name": "staff_id",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "员工名称",
                        "name": "staff_name",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "data",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.JsonResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "allOf": [
                                                {
                                                    "$ref": "#/definitions/page.Page"
                                                },
                                                {
                                                    "type": "object",
                                                    "properties": {
                                                        "List": {
                                                            "$ref": "#/definitions/model.StaffList"
                                                        }
                                                    }
                                                }
                                            ]
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "model.AddConfig": {
            "type": "object",
            "properties": {
                "content": {
                    "type": "string"
                },
                "is_encrypt": {
                    "type": "boolean"
                },
                "is_link_public": {
                    "type": "boolean"
                },
                "is_public": {
                    "type": "boolean"
                },
                "name": {
                    "type": "string"
                },
                "namespace_id": {
                    "description": "传-1代表全部",
                    "type": "integer"
                },
                "project_id": {
                    "type": "integer"
                },
                "public_config_id": {
                    "type": "integer"
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "model.AddNamespace": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                },
                "project_group_id": {
                    "type": "integer"
                },
                "real_time": {
                    "description": "是否灰度",
                    "type": "boolean"
                }
            }
        },
        "model.AddProject": {
            "type": "object",
            "properties": {
                "key": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "project_group_id": {
                    "type": "integer"
                }
            }
        },
        "model.AddProjectGroup": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                }
            }
        },
        "model.AddPublish": {
            "type": "object",
            "properties": {
                "config_id_arr": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "namespace_id": {
                    "type": "integer"
                },
                "project_id": {
                    "type": "integer"
                },
                "publish_data": {
                    "type": "string"
                },
                "publish_type": {
                    "type": "integer"
                }
            }
        },
        "model.AddStaff": {
            "type": "object",
            "properties": {
                "name": {
                    "description": "员工标识",
                    "type": "string"
                }
            }
        },
        "model.ConfigCopy": {
            "type": "object",
            "properties": {
                "config_id": {
                    "type": "integer"
                },
                "op": {
                    "description": "1 转为副本 2关联公共配置",
                    "type": "integer"
                }
            }
        },
        "model.ConfigHistoryList": {
            "type": "object",
            "properties": {
                "config_id": {
                    "type": "integer"
                },
                "content": {
                    "type": "string"
                },
                "create_by": {
                    "type": "integer"
                },
                "create_by_name": {
                    "type": "string"
                },
                "create_time": {
                    "type": "integer"
                },
                "reversion": {
                    "type": "integer"
                }
            }
        },
        "model.ConfigInfo": {
            "type": "object",
            "properties": {
                "config_id": {
                    "type": "integer"
                },
                "config_key": {
                    "type": "string"
                },
                "content": {
                    "type": "string"
                },
                "is_copy": {
                    "type": "boolean"
                },
                "is_encrypt": {
                    "type": "boolean"
                },
                "is_link_public": {
                    "type": "boolean"
                },
                "is_public": {
                    "type": "boolean"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "model.EditConfig": {
            "type": "object",
            "properties": {
                "config_id": {
                    "type": "integer"
                },
                "content": {
                    "type": "string"
                }
            }
        },
        "model.EditNamespace": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                },
                "namespace_id": {
                    "type": "integer"
                },
                "real_time": {
                    "type": "boolean"
                }
            }
        },
        "model.EditProject": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                },
                "project_id": {
                    "type": "integer"
                }
            }
        },
        "model.EditProjectGroup": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                },
                "project_group_id": {
                    "type": "integer"
                }
            }
        },
        "model.EditStaff": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                },
                "staff_id": {
                    "type": "integer"
                }
            }
        },
        "model.GrantStaff": {
            "type": "object",
            "properties": {
                "project_group_id": {
                    "type": "integer"
                },
                "role": {
                    "type": "integer"
                },
                "staff_id": {
                    "type": "integer"
                }
            }
        },
        "model.NamespaceList": {
            "type": "object",
            "properties": {
                "create_by": {
                    "type": "integer"
                },
                "create_by_name": {
                    "type": "string"
                },
                "create_time": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "namespace_id": {
                    "type": "integer"
                },
                "project_group_id": {
                    "type": "integer"
                },
                "project_group_name": {
                    "type": "string"
                },
                "real_time": {
                    "description": "是否灰度",
                    "type": "boolean"
                }
            }
        },
        "model.ProjectGroupList": {
            "type": "object",
            "properties": {
                "create_by": {
                    "type": "integer"
                },
                "create_by_name": {
                    "type": "string"
                },
                "create_time": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "project_group_id": {
                    "type": "integer"
                }
            }
        },
        "model.ProjectList": {
            "type": "object",
            "properties": {
                "create_by": {
                    "type": "integer"
                },
                "create_by_name": {
                    "type": "string"
                },
                "create_time": {
                    "type": "integer"
                },
                "key": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "project_group_id": {
                    "type": "integer"
                },
                "project_group_name": {
                    "type": "string"
                },
                "project_id": {
                    "type": "integer"
                }
            }
        },
        "model.ProjectTree": {
            "type": "object",
            "properties": {
                "nodes": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.TreeNode"
                    }
                }
            }
        },
        "model.PublishConfigList": {
            "type": "object",
            "properties": {
                "create_by": {
                    "type": "integer"
                },
                "create_by_name": {
                    "type": "string"
                },
                "create_time": {
                    "type": "integer"
                },
                "namespace_id": {
                    "type": "integer"
                },
                "namespace_name": {
                    "type": "string"
                },
                "publish_configs": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "publish_id": {
                    "type": "integer"
                },
                "publish_type": {
                    "type": "integer"
                },
                "publish_type_str": {
                    "type": "string"
                },
                "status": {
                    "type": "integer"
                },
                "status_str": {
                    "type": "string"
                }
            }
        },
        "model.RollbackConfig": {
            "type": "object",
            "properties": {
                "history_id": {
                    "type": "integer"
                }
            }
        },
        "model.RollbackPublish": {
            "type": "object",
            "properties": {
                "publish_id": {
                    "type": "integer"
                }
            }
        },
        "model.StaffList": {
            "type": "object",
            "properties": {
                "create_time": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "roles": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.StaffRole"
                    }
                },
                "staff_id": {
                    "type": "integer"
                }
            }
        },
        "model.StaffRole": {
            "type": "object",
            "properties": {
                "project_group_id": {
                    "type": "integer"
                },
                "project_group_name": {
                    "type": "string"
                },
                "role": {
                    "type": "integer"
                },
                "role_info": {
                    "type": "string"
                }
            }
        },
        "model.TreeNode": {
            "type": "object",
            "properties": {
                "children": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.TreeNode"
                    }
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "real_time": {
                    "description": "false 代表可发布",
                    "type": "boolean"
                },
                "type": {
                    "type": "integer"
                }
            }
        },
        "page.Page": {
            "type": "object",
            "properties": {
                "count": {
                    "type": "integer"
                },
                "list": {}
            }
        },
        "response.JsonResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "description": "业务码",
                    "type": "integer"
                },
                "data": {},
                "message": {
                    "description": "描述信息",
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "ApiKeyAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

type swaggerInfo struct {
	Version     string
	Host        string
	BasePath    string
	Schemes     []string
	Title       string
	Description string
}

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = swaggerInfo{
	Version:     "1.0",
	Host:        "localhost:8080",
	BasePath:    "",
	Schemes:     []string{},
	Title:       "配置中心",
	Description: "配置中心接口设计文档",
}

type s struct{}

func (s *s) ReadDoc() string {
	sInfo := SwaggerInfo
	sInfo.Description = strings.Replace(sInfo.Description, "\n", "\\n", -1)

	t, err := template.New("swagger_info").Funcs(template.FuncMap{
		"marshal": func(v interface{}) string {
			a, _ := json.Marshal(v)
			return string(a)
		},
		"escape": func(v interface{}) string {
			// escape tabs
			str := strings.Replace(v.(string), "\t", "\\t", -1)
			// replace " with \", and if that results in \\", replace that with \\\"
			str = strings.Replace(str, "\"", "\\\"", -1)
			return strings.Replace(str, "\\\\\"", "\\\\\\\"", -1)
		},
	}).Parse(doc)
	if err != nil {
		return doc
	}

	var tpl bytes.Buffer
	if err := t.Execute(&tpl, sInfo); err != nil {
		return doc
	}

	return tpl.String()
}

func init() {
	swag.Register("swagger", &s{})
}
