[jwt]
expireDuration = "12h"
secret = "i1ydX9RtHyuJTrw7frcu"
type = "refresh_token"
refreshDuration = "168h"

[mysql]
[mysql.base]
connMaxLifeTime = "3m"
maxIdleConn = 30
maxOpenConn = 60
addr = "127.0.0.1:3306"
name = "sail"
pass = "root"
user = "root"

[etcd]
endpoints = ["127.0.0.1:2379", "127.0.0.1:12379", "127.0.0.1:22379"]
username = ""
password = ""
dialTimeout = "10s"
dialKeepAlive = "1m"
dialKeepAliveTimeout = "5s"

[log]
logPath = "./services.log"
level = "DEBUG" # DEBUG INFO WARN ERROR
stdout = true
jsonFormat = true

[server]
serverName = "sail"
host = ":8108"
pprof = true
historyListLen = 50

[jaeger]
udpEndpoint = "http://127.0.0.1:14268/api/traces"
stdOut = false

[sdk]
configFilePath = "."
logLevel = "WARN"
MergeConfig = false