[jwt]
expireDuration = "2h"
secret = "i1ydX9RtHyuJTrw7frcu"
#type = "refresh_token"
type = "black_list"

[mysql]
[mysql.base]
connMaxLifeTime = "60s"
maxIdleConn = 30
maxOpenConn = 60
addr = "127.0.0.1:3306"
name = "sail"
pass = "root"
user = "root"

[redis]
addr = "127.0.0.1:6379"
db = "0"
maxRetries = 3
minIdleConn = 60
pass = "redis"
poolSize = 120

[log]
logPath = "./services.log"
level = "DEBUG" # DEBUG INFO WARN ERROR
stdout = true
jsonFormat = true

[server]
serverName = "sail"
host = ":8108"
pprof = true

[jaeger]
udpEndpoint = "http://tempo.kube-ops.svc.cluster.local:14268/api/traces"
stdOut = false