// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package api

import (
	"github.com/HYY-yu/sail/internal/service/sail/api/handler"
	"github.com/HYY-yu/sail/internal/service/sail/api/repo"
	"github.com/HYY-yu/sail/internal/service/sail/api/svc"
	"github.com/HYY-yu/seckill.pkg/cache"
	"github.com/HYY-yu/seckill.pkg/db"
)

// Injectors from wire.go:

// initHandlers init Handlers.
func initHandlers(d db.Repo, c cache.Repo) (*Handlers, error) {
	projectGroupRepo := repo.NewProjectGroupRepo()
	staffRepo := repo.NewStaffRepo()
	projectGroupSvc := svc.NewProjectGroupSvc(d, projectGroupRepo, staffRepo)
	projectGroupHandler := handler.NewProjectGroupHandler(projectGroupSvc)
	staffGroupRelRepo := repo.NewStaffGroupRelRepo()
	staffSvc := svc.NewStaffSvc(d, staffRepo, staffGroupRelRepo, projectGroupRepo)
	staffHandler := handler.NewStaffHandler(staffSvc)
	loginSvc := svc.NewLoginSvc(d, staffRepo)
	loginHandler := handler.NewLoginHandler(loginSvc)
	projectRepo := repo.NewProjectRepo()
	projectSvc := svc.NewProjectSvc(d, projectRepo, projectGroupRepo, staffRepo)
	projectHandler := handler.NewProjectHandler(projectSvc)
	namespaceRepo := repo.NewNamespaceRepo()
	namespaceSvc := svc.NewNamespaceSvc(d, namespaceRepo, projectGroupRepo, staffRepo)
	namespaceHandler := handler.NewNamespaceHandler(namespaceSvc)
	handlers := NewHandlers(projectGroupHandler, staffHandler, loginHandler, projectHandler, namespaceHandler)
	return handlers, nil
}
