// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package api

import (
	"github.com/HYY-yu/seckill.pkg/cache"
	"github.com/HYY-yu/seckill.pkg/db"
	"go.uber.org/zap"
)

// Injectors from wire.go:

// initHandlers init Handlers.
func initHandlers(l *zap.Logger, d db.Repo, c cache.Repo) (*Handlers, error) {
	handlers := NewHandlers()
	return handlers, nil
}
