// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package api

import (
	"github.com/HYY-yu/sail/internal/service/sail/api/handler"
	"github.com/HYY-yu/sail/internal/service/sail/api/repo"
	"github.com/HYY-yu/sail/internal/service/sail/api/svc"
	"github.com/HYY-yu/sail/internal/service/sail/api/svc_publish"
	"github.com/HYY-yu/sail/internal/service/sail/storage"
	"github.com/HYY-yu/seckill.pkg/cache"
	"github.com/HYY-yu/seckill.pkg/db"
)

// Injectors from wire.go:

// initHandlers init Handlers.
func initHandlers(d db.Repo, c cache.Repo, store storage.Repo) (*Handlers, error) {
	projectGroupRepo := repo.NewProjectGroupRepo()
	staffRepo := repo.NewStaffRepo()
	projectGroupSvc := svc.NewProjectGroupSvc(d, projectGroupRepo, staffRepo)
	projectGroupHandler := handler.NewProjectGroupHandler(projectGroupSvc)
	staffGroupRelRepo := repo.NewStaffGroupRelRepo()
	staffSvc := svc.NewStaffSvc(d, staffRepo, staffGroupRelRepo, projectGroupRepo)
	staffHandler := handler.NewStaffHandler(staffSvc)
	loginSvc := svc.NewLoginSvc(d, staffRepo)
	loginHandler := handler.NewLoginHandler(loginSvc)
	projectRepo := repo.NewProjectRepo()
	projectSvc := svc.NewProjectSvc(d, projectRepo, projectGroupRepo, staffRepo)
	projectHandler := handler.NewProjectHandler(projectSvc)
	namespaceRepo := repo.NewNamespaceRepo()
	namespaceSvc := svc.NewNamespaceSvc(d, namespaceRepo, projectGroupRepo, staffRepo)
	namespaceHandler := handler.NewNamespaceHandler(namespaceSvc)
	configRepo := repo.NewConfigRepo()
	configHistoryRepo := repo.NewConfigHistoryRepo()
	configLinkRepo := repo.NewConfigLinkRepo()
	publishConfigRepo := repo.NewPublishConfigRepo()
	configSvc := svc.NewConfigSvc(d, store, configRepo, configHistoryRepo, configLinkRepo, projectRepo, namespaceRepo, staffRepo, publishConfigRepo)
	configHandler := handler.NewConfigHandler(configSvc)
	indexHandler := handler.NewIndexHandler(projectGroupSvc, namespaceSvc, configSvc)
	publishRepo := repo.NewPublishRepo()
	publishSvc := svc_publish.NewPublishSvc(d, store, configSvc, publishRepo, publishConfigRepo)
	testDataSvc := svc.NewTestDataSvc(d, namespaceSvc, projectSvc, configSvc)
	envTestHandler := handler.NewEnvTestHandler(testDataSvc)
	handlers := NewHandlers(projectGroupHandler, staffHandler, loginHandler, projectHandler, namespaceHandler, configHandler, indexHandler, publishSvc, configSvc, envTestHandler)
	return handlers, nil
}
