# permissions for end users to view configmaprequests.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: configmaprequest-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: operator
    app.kubernetes.io/part-of: operator
    app.kubernetes.io/managed-by: kustomize
  name: configmaprequest-viewer-role
rules:
- apiGroups:
  - cmr.sail.hyy-yu.space
  resources:
  - configmaprequests
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cmr.sail.hyy-yu.space
  resources:
  - configmaprequests/status
  verbs:
  - get
