// Code generated by gormt. DO NOT EDIT.
package repo

import (
	"context"

	"gorm.io/gorm"
)

var globalIsRelated bool = true // 全局预加载

// prepare for other
type _BaseMgr struct {
	*gorm.DB
	ctx       context.Context
	cancel    context.CancelFunc
	isRelated bool
}

// Cancel cancel context
func (obj *_BaseMgr) Cancel(c context.Context) {
	obj.cancel()
}

// GetDB get gorm.DB info
func (obj *_BaseMgr) GetDB() *gorm.DB {
	return obj.DB
}

// GetIsRelated Query foreign key Association.获取是否查询外键关联(gorm.Related)
func (obj *_BaseMgr) GetIsRelated() bool {
	return obj.isRelated
}

// SetIsRelated Query foreign key Association.设置是否查询外键关联(gorm.Related)
func (obj *_BaseMgr) SetIsRelated(b bool) {
	obj.isRelated = b
}

type options struct {
	query map[string]queryData
}

type queryData struct {
	data interface{}
	cond string
}

// Option overrides behavior of Connect.
type Option interface {
	apply(*options)
}

type optionFunc func(*options)

func (f optionFunc) apply(o *options) {
	f(o)
}

// OpenRelated 打开全局预加载
func OpenRelated() {
	globalIsRelated = true
}

// CloseRelated 关闭全局预加载
func CloseRelated() {
	globalIsRelated = true
}

// -------- sql where helper ----------

// sort 不能改变 obj.DB ，变成已初始化的DB，将会对后续语句执行造成影响
// 因此主动返回 已初始化的DB ，表示：此sort方法只能使用一次
func (obj *_BaseMgr) sort(userSort, defaultSort string) *gorm.DB {
	if len(userSort) > 0 {
		return obj.DB.Order(userSort)
	} else {
		if len(defaultSort) > 0 {
			return obj.DB.Order(defaultSort)
		}
	}
	return obj.DB
}
