package repo

import (
	"context"
	"fmt"
	"time"

	"gorm.io/gorm"

	"github.com/HYY-yu/sail/internal/service/sail/model"
)

// Code generated by gormt. DO NOT EDIT.

type _PublishConfigMgr struct {
	*_BaseMgr
}

// PublishConfigMgr open func
func PublishConfigMgr(ctx context.Context, db *gorm.DB) *_PublishConfigMgr {
	if db == nil {
		panic(fmt.Errorf("PublishConfigMgr need init by db"))
	}
	ctx, cancel := context.WithCancel(ctx)
	return &_PublishConfigMgr{_BaseMgr: &_BaseMgr{DB: db.Table("publish_config").WithContext(ctx), isRelated: globalIsRelated, ctx: ctx, cancel: cancel}}
}

func (obj *_PublishConfigMgr) WithSelects(idName string, selects ...string) *_PublishConfigMgr {
	if len(selects) > 0 {
		if len(idName) > 0 {
			selects = append(selects, idName)
		}
		// 对Select进行去重
		selectMap := make(map[string]int, len(selects))
		for _, e := range selects {
			if _, ok := selectMap[e]; !ok {
				selectMap[e] = 1
			}
		}

		newSelects := make([]string, 0, len(selects))
		for k := range selectMap {
			if len(k) > 0 {
				newSelects = append(newSelects, k)
			}
		}
		obj.DB = obj.DB.Select(newSelects)
	}
	return obj
}

func (obj *_PublishConfigMgr) WithOptions(opts ...Option) *_PublishConfigMgr {
	options := options{
		query: make(map[string]queryData, len(opts)),
	}
	for _, o := range opts {
		o.apply(&options)
	}
	for k, v := range options.query {
		obj.DB = obj.DB.Where(k+" "+v.cond, v.data)
	}
	return obj
}

// GetTableName get sql table name.获取数据库名字
func (obj *_PublishConfigMgr) GetTableName() string {
	return "publish_config"
}

// Reset 重置gorm会话
func (obj *_PublishConfigMgr) Reset() *_PublishConfigMgr {
	obj.new()
	return obj
}

// Get 获取
func (obj *_PublishConfigMgr) Get() (result model.PublishConfig, err error) {
	err = obj.DB.Find(&result).Error

	return
}

// Gets 获取批量结果
func (obj *_PublishConfigMgr) Gets() (results []model.PublishConfig, err error) {
	err = obj.DB.Find(&results).Error

	return
}

func (obj *_PublishConfigMgr) Count(count *int64) (tx *gorm.DB) {
	return obj.DB.Count(count)
}

func (obj *_PublishConfigMgr) HasRecord() (bool, error) {
	var count int64
	err := obj.DB.Count(&count).Error
	if err != nil {
		return false, err
	}
	return count != 0, nil
}

// WithID id获取
func (obj *_PublishConfigMgr) WithID(id int, cond ...string) Option {
	return optionFunc(func(o *options) {
		if len(cond) == 0 {
			cond = []string{" = ? "}
		}
		o.query["id"] = queryData{
			cond: cond[0],
			data: id,
		}
	})
}

// WithProjectID project_id获取
func (obj *_PublishConfigMgr) WithProjectID(projectID int, cond ...string) Option {
	return optionFunc(func(o *options) {
		if len(cond) == 0 {
			cond = []string{" = ? "}
		}
		o.query["project_id"] = queryData{
			cond: cond[0],
			data: projectID,
		}
	})
}

// WithNamespaceID namespace_id获取
func (obj *_PublishConfigMgr) WithNamespaceID(namespaceID int, cond ...string) Option {
	return optionFunc(func(o *options) {
		if len(cond) == 0 {
			cond = []string{" = ? "}
		}
		o.query["namespace_id"] = queryData{
			cond: cond[0],
			data: namespaceID,
		}
	})
}

// WithPublishType publish_type获取 发布方式
func (obj *_PublishConfigMgr) WithPublishType(publishType int, cond ...string) Option {
	return optionFunc(func(o *options) {
		if len(cond) == 0 {
			cond = []string{" = ? "}
		}
		o.query["publish_type"] = queryData{
			cond: cond[0],
			data: publishType,
		}
	})
}

// WithPublishData publish_data获取 发布数据
func (obj *_PublishConfigMgr) WithPublishData(publishData string, cond ...string) Option {
	return optionFunc(func(o *options) {
		if len(cond) == 0 {
			cond = []string{" = ? "}
		}
		o.query["publish_data"] = queryData{
			cond: cond[0],
			data: publishData,
		}
	})
}

// WithPublishConfigIDs publish_config_ids获取
func (obj *_PublishConfigMgr) WithPublishConfigIDs(publishConfigIDs string, cond ...string) Option {
	return optionFunc(func(o *options) {
		if len(cond) == 0 {
			cond = []string{" = ? "}
		}
		o.query["publish_config_ids"] = queryData{
			cond: cond[0],
			data: publishConfigIDs,
		}
	})
}

// WithStatus status获取
func (obj *_PublishConfigMgr) WithStatus(status int, cond ...string) Option {
	return optionFunc(func(o *options) {
		if len(cond) == 0 {
			cond = []string{" = ? "}
		}
		o.query["status"] = queryData{
			cond: cond[0],
			data: status,
		}
	})
}

// WithCreateTime create_time获取
func (obj *_PublishConfigMgr) WithCreateTime(createTime time.Time, cond ...string) Option {
	return optionFunc(func(o *options) {
		if len(cond) == 0 {
			cond = []string{" = ? "}
		}
		o.query["create_time"] = queryData{
			cond: cond[0],
			data: createTime,
		}
	})
}

// WithUpdateTime update_time获取
func (obj *_PublishConfigMgr) WithUpdateTime(updateTime time.Time, cond ...string) Option {
	return optionFunc(func(o *options) {
		if len(cond) == 0 {
			cond = []string{" = ? "}
		}
		o.query["update_time"] = queryData{
			cond: cond[0],
			data: updateTime,
		}
	})
}

func (obj *_PublishConfigMgr) CreatePublishConfig(bean *model.PublishConfig) (err error) {
	err = obj.DB.Create(bean).Error

	return
}

func (obj *_PublishConfigMgr) UpdatePublishConfig(bean *model.PublishConfig) (err error) {
	err = obj.DB.Updates(bean).Error

	return
}

func (obj *_PublishConfigMgr) DeletePublishConfig(bean *model.PublishConfig) (err error) {
	err = obj.DB.Delete(bean).Error

	return
}
