package repo

import (
	"context"
	"fmt"
	"gorm.io/gorm"
	"time"
)

// Code generated by gormt. DO NOT EDIT.

type _StaffGroupMgr struct {
	*_BaseMgr
}

// StaffGroupMgr open func
func StaffGroupMgr(db *gorm.DB) *_StaffGroupMgr {
	if db == nil {
		panic(fmt.Errorf("StaffGroupMgr need init by db"))
	}
	ctx, cancel := context.WithCancel(context.Background())
	return &_StaffGroupMgr{_BaseMgr: &_BaseMgr{DB: db.Table("staff_group"), isRelated: globalIsRelated, ctx: ctx, cancel: cancel, timeout: -1}}
}

// WithContext set context to db
func (obj *_StaffGroupMgr) WithContext(c context.Context) *_StaffGroupMgr {
	if c != nil {
		obj.ctx = c
	}
	return obj
}

func (obj *_StaffGroupMgr) WithSelects(idName string, selects ...string) *_StaffGroupMgr {
	if len(selects) > 0 {
		if len(idName) > 0 {
			selects = append(selects, idName)
		}
		// 对Select进行去重
		selectMap := make(map[string]int, len(selects))
		for _, e := range selects {
			if _, ok := selectMap[e]; !ok {
				selectMap[e] = 1
			}
		}

		newSelects := make([]string, 0, len(selects))
		for k := range selectMap {
			if len(k) > 0 {
				newSelects = append(newSelects, k)
			}
		}
		obj.DB = obj.DB.Select(newSelects)
	}
	return obj
}

func (obj *_StaffGroupMgr) WithOmit(omit ...string) *_StaffGroupMgr {
	if len(omit) > 0 {
		obj.DB = obj.DB.Omit(omit...)
	}
	return obj
}

func (obj *_StaffGroupMgr) WithOptions(opts ...Option) *_StaffGroupMgr {
	options := options{
		query: make(map[string]interface{}, len(opts)),
	}
	for _, o := range opts {
		o.apply(&options)
	}
	obj.DB = obj.DB.Where(options.query)
	return obj
}

// GetTableName get sql table name.获取数据库名字
func (obj *_StaffGroupMgr) GetTableName() string {
	return "staff_group"
}

// Reset 重置gorm会话
func (obj *_StaffGroupMgr) Reset() *_StaffGroupMgr {
	obj.new()
	return obj
}

// Get 获取
func (obj *_StaffGroupMgr) Get() (result StaffGroup, err error) {
	err = obj.DB.WithContext(obj.ctx).Model(StaffGroup{}).Find(&result).Error

	return
}

// Gets 获取批量结果
func (obj *_StaffGroupMgr) Gets() (results []*StaffGroup, err error) {
	err = obj.DB.WithContext(obj.ctx).Model(StaffGroup{}).Find(&results).Error

	return
}

func (obj *_StaffGroupMgr) Count(count *int64) (tx *gorm.DB) {
	return obj.DB.WithContext(obj.ctx).Model(StaffGroup{}).Count(count)
}

// WithID id获取
func (obj *_StaffGroupMgr) WithID(id int) Option {
	return optionFunc(func(o *options) { o.query["id"] = id })
}

// WithName name获取
func (obj *_StaffGroupMgr) WithName(name string) Option {
	return optionFunc(func(o *options) { o.query["name"] = name })
}

// WithCreateTime create_time获取
func (obj *_StaffGroupMgr) WithCreateTime(createTime time.Time) Option {
	return optionFunc(func(o *options) { o.query["create_time"] = createTime })
}

// WithCreateBy create_by获取
func (obj *_StaffGroupMgr) WithCreateBy(createBy int) Option {
	return optionFunc(func(o *options) { o.query["create_by"] = createBy })
}

// WithDeleteTime delete_time获取
func (obj *_StaffGroupMgr) WithDeleteTime(deleteTime int) Option {
	return optionFunc(func(o *options) { o.query["delete_time"] = deleteTime })
}

// GetFromID 通过id获取内容
func (obj *_StaffGroupMgr) GetFromID(id int) (result StaffGroup, err error) {
	err = obj.DB.WithContext(obj.ctx).Model(StaffGroup{}).Where("`id` = ?", id).Find(&result).Error

	return
}

// GetBatchFromID 批量查找
func (obj *_StaffGroupMgr) GetBatchFromID(ids []int) (results []*StaffGroup, err error) {
	err = obj.DB.WithContext(obj.ctx).Model(StaffGroup{}).Where("`id` IN (?)", ids).Find(&results).Error

	return
}

// GetFromName 通过name获取内容
func (obj *_StaffGroupMgr) GetFromName(name string) (results []*StaffGroup, err error) {
	err = obj.DB.WithContext(obj.ctx).Model(StaffGroup{}).Where("`name` = ?", name).Find(&results).Error

	return
}

// GetBatchFromName 批量查找
func (obj *_StaffGroupMgr) GetBatchFromName(names []string) (results []*StaffGroup, err error) {
	err = obj.DB.WithContext(obj.ctx).Model(StaffGroup{}).Where("`name` IN (?)", names).Find(&results).Error

	return
}

// GetFromCreateTime 通过create_time获取内容
func (obj *_StaffGroupMgr) GetFromCreateTime(createTime time.Time) (results []*StaffGroup, err error) {
	err = obj.DB.WithContext(obj.ctx).Model(StaffGroup{}).Where("`create_time` = ?", createTime).Find(&results).Error

	return
}

// GetBatchFromCreateTime 批量查找
func (obj *_StaffGroupMgr) GetBatchFromCreateTime(createTimes []time.Time) (results []*StaffGroup, err error) {
	err = obj.DB.WithContext(obj.ctx).Model(StaffGroup{}).Where("`create_time` IN (?)", createTimes).Find(&results).Error

	return
}

// GetFromCreateBy 通过create_by获取内容
func (obj *_StaffGroupMgr) GetFromCreateBy(createBy int) (results []*StaffGroup, err error) {
	err = obj.DB.WithContext(obj.ctx).Model(StaffGroup{}).Where("`create_by` = ?", createBy).Find(&results).Error

	return
}

// GetBatchFromCreateBy 批量查找
func (obj *_StaffGroupMgr) GetBatchFromCreateBy(createBys []int) (results []*StaffGroup, err error) {
	err = obj.DB.WithContext(obj.ctx).Model(StaffGroup{}).Where("`create_by` IN (?)", createBys).Find(&results).Error

	return
}

// GetFromDeleteTime 通过delete_time获取内容
func (obj *_StaffGroupMgr) GetFromDeleteTime(deleteTime int) (results []*StaffGroup, err error) {
	err = obj.DB.WithContext(obj.ctx).Model(StaffGroup{}).Where("`delete_time` = ?", deleteTime).Find(&results).Error

	return
}

// GetBatchFromDeleteTime 批量查找
func (obj *_StaffGroupMgr) GetBatchFromDeleteTime(deleteTimes []int) (results []*StaffGroup, err error) {
	err = obj.DB.WithContext(obj.ctx).Model(StaffGroup{}).Where("`delete_time` IN (?)", deleteTimes).Find(&results).Error

	return
}

func (obj *_StaffGroupMgr) CreateStaffGroup(bean *StaffGroup) (err error) {
	err = obj.DB.WithContext(obj.ctx).Model(StaffGroup{}).Create(bean).Error

	return
}

func (obj *_StaffGroupMgr) UpdateStaffGroup(bean *StaffGroup) (err error) {
	err = obj.DB.WithContext(obj.ctx).Model(bean).Updates(bean).Error

	return
}

func (obj *_StaffGroupMgr) DeleteStaffGroup(bean *StaffGroup) (err error) {
	err = obj.DB.WithContext(obj.ctx).Model(StaffGroup{}).Delete(bean).Error

	return
}
