package repo

import (
	"context"
	"fmt"
	"github.com/HYY-yu/sail/internal/service/sail/model"
	"gorm.io/gorm"
)

// Code generated by gormt. DO NOT EDIT.

// 非线程安全

type _ConfigLinkMgr struct {
	*_BaseMgr
}

// ConfigLinkMgr open func
func ConfigLinkMgr(ctx context.Context, db *gorm.DB) *_ConfigLinkMgr {
	if db == nil {
		panic(fmt.Errorf("ConfigLinkMgr need init by db"))
	}
	ctx, cancel := context.WithCancel(ctx)
	return &_ConfigLinkMgr{_BaseMgr: &_BaseMgr{DB: db.Table("config_link").WithContext(ctx), isRelated: globalIsRelated, ctx: ctx, cancel: cancel}}
}

func (obj *_ConfigLinkMgr) WithSelects(idName string, selects ...string) *_ConfigLinkMgr {
	if len(idName) > 0 {
		selects = append(selects, idName)
	}
	if len(selects) > 0 {
		// 对Select进行去重
		selectMap := make(map[string]int, len(selects))
		for _, e := range selects {
			if _, ok := selectMap[e]; !ok {
				selectMap[e] = 1
			}
		}

		newSelects := make([]string, 0, len(selects))
		for k := range selectMap {
			if len(k) > 0 {
				newSelects = append(newSelects, k)
			}
		}
		obj.DB = obj.DB.Select(newSelects)
	}
	return obj
}

func (obj *_ConfigLinkMgr) WithOptions(opts ...Option) *_ConfigLinkMgr {
	obj.Reset()

	options := options{
		query: make(map[string]queryData, len(opts)),
	}
	for _, o := range opts {
		o.apply(&options)
	}
	for k, v := range options.query {
		if v.data == nil {
			obj.DB = obj.DB.Where(k + " " + v.cond)
		} else {
			obj.DB = obj.DB.Where(k+" "+v.cond, v.data)
		}
	}
	return obj
}

// GetTableName get sql table name.获取表名字
func (obj *_ConfigLinkMgr) GetTableName() string {
	return "config_link"
}

// Tx 开启事务会话
func (obj *_ConfigLinkMgr) Tx(tx *gorm.DB) *_ConfigLinkMgr {
	obj.DB = tx.Table(obj.GetTableName()).WithContext(obj.ctx)
	return obj
}

// WithPrepareStmt 开启语句 PrepareStmt 功能
// 接下来执行的SQL将会是PrepareStmt的
func (obj *_ConfigLinkMgr) WithPrepareStmt() {
	obj.DB = obj.DB.Session(&gorm.Session{Context: obj.ctx, PrepareStmt: true})
}

// Reset 重置gorm会话
func (obj *_ConfigLinkMgr) Reset() *_ConfigLinkMgr {
	obj.DB = obj.DB.Session(&gorm.Session{NewDB: true, Context: obj.ctx}).Table(obj.GetTableName())
	return obj
}

// Get 获取
func (obj *_ConfigLinkMgr) Get() (result model.ConfigLink, err error) {
	err = obj.DB.Find(&result).Error

	return
}

// Gets 获取批量结果
func (obj *_ConfigLinkMgr) Gets() (results []model.ConfigLink, err error) {
	err = obj.DB.Find(&results).Error

	return
}

// Catch 必须获取结果（单条）
func (obj *_ConfigLinkMgr) Catch() (results model.ConfigLink, err error) {
	err = obj.DB.Take(&results).Error

	return
}

func (obj *_ConfigLinkMgr) Count() (count int64, err error) {
	err = obj.DB.Count(&count).Error

	return
}

func (obj *_ConfigLinkMgr) HasRecord() (bool, error) {
	count, err := obj.Count()
	if err != nil {
		return false, err
	}
	return count != 0, nil
}

// WithID id获取
func (obj *_ConfigLinkMgr) WithID(id interface{}, cond ...string) Option {
	return optionFunc(func(o *options) {
		if len(cond) == 0 {
			cond = []string{" = ? "}
		}
		o.query["id"] = queryData{
			cond: cond[0],
			data: id,
		}
	})
}

// WithConfigID config_id获取
func (obj *_ConfigLinkMgr) WithConfigID(configID interface{}, cond ...string) Option {
	return optionFunc(func(o *options) {
		if len(cond) == 0 {
			cond = []string{" = ? "}
		}
		o.query["config_id"] = queryData{
			cond: cond[0],
			data: configID,
		}
	})
}

// WithPublicConfigID public_config_id获取
func (obj *_ConfigLinkMgr) WithPublicConfigID(publicConfigID interface{}, cond ...string) Option {
	return optionFunc(func(o *options) {
		if len(cond) == 0 {
			cond = []string{" = ? "}
		}
		o.query["public_config_id"] = queryData{
			cond: cond[0],
			data: publicConfigID,
		}
	})
}

func (obj *_ConfigLinkMgr) CreateConfigLink(bean *model.ConfigLink) (err error) {
	err = obj.DB.Create(bean).Error

	return
}

func (obj *_ConfigLinkMgr) UpdateConfigLink(bean *model.ConfigLink) (err error) {
	err = obj.DB.Updates(bean).Error

	return
}

func (obj *_ConfigLinkMgr) DeleteConfigLink(bean *model.ConfigLink) (err error) {
	err = obj.DB.Delete(bean).Error

	return
}

// FetchIndexByPublicConfigID  获取多个内容
func (obj *_ConfigLinkMgr) FetchIndexByPublicConfigID(publicConfigID int) (results []*model.ConfigLink, err error) {
	err = obj.DB.WithContext(obj.ctx).Model(model.ConfigLink{}).Where("`public_config_id` = ?", publicConfigID).Find(&results).Error

	return
}
