package repo

import (
	"context"
	"fmt"
	"time"

	"gorm.io/gorm"

	"github.com/HYY-yu/sail/internal/service/sail/model"
)

// Code generated by gormt. DO NOT EDIT.

type _NamespaceMgr struct {
	*_BaseMgr
}

// NamespaceMgr open func
func NamespaceMgr(db *gorm.DB) *_NamespaceMgr {
	if db == nil {
		panic(fmt.Errorf("NamespaceMgr need init by db"))
	}
	ctx, cancel := context.WithCancel(context.Background())
	return &_NamespaceMgr{_BaseMgr: &_BaseMgr{DB: db.Table("namespace"), isRelated: globalIsRelated, ctx: ctx, cancel: cancel, timeout: -1}}
}

// WithContext set context to db
func (obj *_NamespaceMgr) WithContext(c context.Context) *_NamespaceMgr {
	if c != nil {
		obj.ctx = c
	}
	return obj
}

func (obj *_NamespaceMgr) WithSelects(idName string, selects ...string) *_NamespaceMgr {
	if len(selects) > 0 {
		if len(idName) > 0 {
			selects = append(selects, idName)
		}
		// 对Select进行去重
		selectMap := make(map[string]int, len(selects))
		for _, e := range selects {
			if _, ok := selectMap[e]; !ok {
				selectMap[e] = 1
			}
		}

		newSelects := make([]string, 0, len(selects))
		for k := range selectMap {
			if len(k) > 0 {
				newSelects = append(newSelects, k)
			}
		}
		obj.DB = obj.DB.Select(newSelects)
	}
	return obj
}

func (obj *_NamespaceMgr) WithOmit(omit ...string) *_NamespaceMgr {
	if len(omit) > 0 {
		obj.DB = obj.DB.Omit(omit...)
	}
	return obj
}

func (obj *_NamespaceMgr) WithOptions(opts ...Option) *_NamespaceMgr {
	options := options{
		query: make(map[string]interface{}, len(opts)),
	}
	for _, o := range opts {
		o.apply(&options)
	}
	obj.DB = obj.DB.Where(options.query)
	return obj
}

// GetTableName get sql table name.获取数据库名字
func (obj *_NamespaceMgr) GetTableName() string {
	return "namespace"
}

// Reset 重置gorm会话
func (obj *_NamespaceMgr) Reset() *_NamespaceMgr {
	obj.new()
	return obj
}

// Get 获取
func (obj *_NamespaceMgr) Get() (result model.Namespace, err error) {
	err = obj.DB.WithContext(obj.ctx).Model(model.Namespace{}).Find(&result).Error

	return
}

// Gets 获取批量结果
func (obj *_NamespaceMgr) Gets() (results []*model.Namespace, err error) {
	err = obj.DB.WithContext(obj.ctx).Model(model.Namespace{}).Find(&results).Error

	return
}

func (obj *_NamespaceMgr) Count(count *int64) (tx *gorm.DB) {
	return obj.DB.WithContext(obj.ctx).Model(model.Namespace{}).Count(count)
}

// WithID id获取
func (obj *_NamespaceMgr) WithID(id int) Option {
	return optionFunc(func(o *options) { o.query["id"] = id })
}

// WithProjectGroupID project_group_id获取
func (obj *_NamespaceMgr) WithProjectGroupID(projectGroupID int) Option {
	return optionFunc(func(o *options) { o.query["project_group_id"] = projectGroupID })
}

// WithName name获取
func (obj *_NamespaceMgr) WithName(name string) Option {
	return optionFunc(func(o *options) { o.query["name"] = name })
}

// WithRealTime real_time获取 是否是实时发布
func (obj *_NamespaceMgr) WithRealTime(realTime bool) Option {
	return optionFunc(func(o *options) { o.query["real_time"] = realTime })
}

// WithCreateTime create_time获取
func (obj *_NamespaceMgr) WithCreateTime(createTime time.Time) Option {
	return optionFunc(func(o *options) { o.query["create_time"] = createTime })
}

// WithCreateBy create_by获取
func (obj *_NamespaceMgr) WithCreateBy(createBy int) Option {
	return optionFunc(func(o *options) { o.query["create_by"] = createBy })
}

// WithDeleteTime delete_time获取
func (obj *_NamespaceMgr) WithDeleteTime(deleteTime int) Option {
	return optionFunc(func(o *options) { o.query["delete_time"] = deleteTime })
}

// GetFromID 通过id获取内容
func (obj *_NamespaceMgr) GetFromID(id int) (result model.Namespace, err error) {
	err = obj.DB.WithContext(obj.ctx).Model(model.Namespace{}).Where("`id` = ?", id).Find(&result).Error

	return
}

// GetBatchFromID 批量查找
func (obj *_NamespaceMgr) GetBatchFromID(ids []int) (results []*model.Namespace, err error) {
	err = obj.DB.WithContext(obj.ctx).Model(model.Namespace{}).Where("`id` IN (?)", ids).Find(&results).Error

	return
}

// GetFromProjectGroupID 通过project_group_id获取内容
func (obj *_NamespaceMgr) GetFromProjectGroupID(projectGroupID int) (results []*model.Namespace, err error) {
	err = obj.DB.WithContext(obj.ctx).Model(model.Namespace{}).Where("`project_group_id` = ?", projectGroupID).Find(&results).Error

	return
}

// GetBatchFromProjectGroupID 批量查找
func (obj *_NamespaceMgr) GetBatchFromProjectGroupID(projectGroupIDs []int) (results []*model.Namespace, err error) {
	err = obj.DB.WithContext(obj.ctx).Model(model.Namespace{}).Where("`project_group_id` IN (?)", projectGroupIDs).Find(&results).Error

	return
}

// GetFromName 通过name获取内容
func (obj *_NamespaceMgr) GetFromName(name string) (results []*model.Namespace, err error) {
	err = obj.DB.WithContext(obj.ctx).Model(model.Namespace{}).Where("`name` = ?", name).Find(&results).Error

	return
}

// GetBatchFromName 批量查找
func (obj *_NamespaceMgr) GetBatchFromName(names []string) (results []*model.Namespace, err error) {
	err = obj.DB.WithContext(obj.ctx).Model(model.Namespace{}).Where("`name` IN (?)", names).Find(&results).Error

	return
}

// GetFromRealTime 通过real_time获取内容 是否是实时发布
func (obj *_NamespaceMgr) GetFromRealTime(realTime bool) (results []*model.Namespace, err error) {
	err = obj.DB.WithContext(obj.ctx).Model(model.Namespace{}).Where("`real_time` = ?", realTime).Find(&results).Error

	return
}

// GetBatchFromRealTime 批量查找 是否是实时发布
func (obj *_NamespaceMgr) GetBatchFromRealTime(realTimes []bool) (results []*model.Namespace, err error) {
	err = obj.DB.WithContext(obj.ctx).Model(model.Namespace{}).Where("`real_time` IN (?)", realTimes).Find(&results).Error

	return
}

// GetFromCreateTime 通过create_time获取内容
func (obj *_NamespaceMgr) GetFromCreateTime(createTime time.Time) (results []*model.Namespace, err error) {
	err = obj.DB.WithContext(obj.ctx).Model(model.Namespace{}).Where("`create_time` = ?", createTime).Find(&results).Error

	return
}

// GetBatchFromCreateTime 批量查找
func (obj *_NamespaceMgr) GetBatchFromCreateTime(createTimes []time.Time) (results []*model.Namespace, err error) {
	err = obj.DB.WithContext(obj.ctx).Model(model.Namespace{}).Where("`create_time` IN (?)", createTimes).Find(&results).Error

	return
}

// GetFromCreateBy 通过create_by获取内容
func (obj *_NamespaceMgr) GetFromCreateBy(createBy int) (results []*model.Namespace, err error) {
	err = obj.DB.WithContext(obj.ctx).Model(model.Namespace{}).Where("`create_by` = ?", createBy).Find(&results).Error

	return
}

// GetBatchFromCreateBy 批量查找
func (obj *_NamespaceMgr) GetBatchFromCreateBy(createBys []int) (results []*model.Namespace, err error) {
	err = obj.DB.WithContext(obj.ctx).Model(model.Namespace{}).Where("`create_by` IN (?)", createBys).Find(&results).Error

	return
}

// GetFromDeleteTime 通过delete_time获取内容
func (obj *_NamespaceMgr) GetFromDeleteTime(deleteTime int) (results []*model.Namespace, err error) {
	err = obj.DB.WithContext(obj.ctx).Model(model.Namespace{}).Where("`delete_time` = ?", deleteTime).Find(&results).Error

	return
}

// GetBatchFromDeleteTime 批量查找
func (obj *_NamespaceMgr) GetBatchFromDeleteTime(deleteTimes []int) (results []*model.Namespace, err error) {
	err = obj.DB.WithContext(obj.ctx).Model(model.Namespace{}).Where("`delete_time` IN (?)", deleteTimes).Find(&results).Error

	return
}

func (obj *_NamespaceMgr) CreateNamespace(bean *model.Namespace) (err error) {
	err = obj.DB.WithContext(obj.ctx).Model(model.Namespace{}).Create(bean).Error

	return
}

func (obj *_NamespaceMgr) UpdateNamespace(bean *model.Namespace) (err error) {
	err = obj.DB.WithContext(obj.ctx).Model(bean).Updates(bean).Error

	return
}

func (obj *_NamespaceMgr) DeleteNamespace(bean *model.Namespace) (err error) {
	err = obj.DB.WithContext(obj.ctx).Model(model.Namespace{}).Delete(bean).Error

	return
}
