package repo

import (
	"context"
	"fmt"

	"gorm.io/gorm"

	"github.com/HYY-yu/sail/internal/service/sail/model"
)

// Code generated by gormt. DO NOT EDIT.

type _ConfigLinkMgr struct {
	*_BaseMgr
}

// ConfigLinkMgr open func
func ConfigLinkMgr(db *gorm.DB) *_ConfigLinkMgr {
	if db == nil {
		panic(fmt.Errorf("ConfigLinkMgr need init by db"))
	}
	ctx, cancel := context.WithCancel(context.Background())
	return &_ConfigLinkMgr{_BaseMgr: &_BaseMgr{DB: db.Table("config_link"), isRelated: globalIsRelated, ctx: ctx, cancel: cancel, timeout: -1}}
}

// WithContext set context to db
func (obj *_ConfigLinkMgr) WithContext(c context.Context) *_ConfigLinkMgr {
	if c != nil {
		obj.ctx = c
	}
	return obj
}

func (obj *_ConfigLinkMgr) WithSelects(idName string, selects ...string) *_ConfigLinkMgr {
	if len(selects) > 0 {
		if len(idName) > 0 {
			selects = append(selects, idName)
		}
		// 对Select进行去重
		selectMap := make(map[string]int, len(selects))
		for _, e := range selects {
			if _, ok := selectMap[e]; !ok {
				selectMap[e] = 1
			}
		}

		newSelects := make([]string, 0, len(selects))
		for k := range selectMap {
			if len(k) > 0 {
				newSelects = append(newSelects, k)
			}
		}
		obj.DB = obj.DB.Select(newSelects)
	}
	return obj
}

func (obj *_ConfigLinkMgr) WithOmit(omit ...string) *_ConfigLinkMgr {
	if len(omit) > 0 {
		obj.DB = obj.DB.Omit(omit...)
	}
	return obj
}

func (obj *_ConfigLinkMgr) WithOptions(opts ...Option) *_ConfigLinkMgr {
	options := options{
		query: make(map[string]interface{}, len(opts)),
	}
	for _, o := range opts {
		o.apply(&options)
	}
	obj.DB = obj.DB.Where(options.query)
	return obj
}

// GetTableName get sql table name.获取数据库名字
func (obj *_ConfigLinkMgr) GetTableName() string {
	return "config_link"
}

// Reset 重置gorm会话
func (obj *_ConfigLinkMgr) Reset() *_ConfigLinkMgr {
	obj.new()
	return obj
}

// Get 获取
func (obj *_ConfigLinkMgr) Get() (result model.ConfigLink, err error) {
	err = obj.DB.WithContext(obj.ctx).Model(model.ConfigLink{}).Find(&result).Error

	return
}

// Gets 获取批量结果
func (obj *_ConfigLinkMgr) Gets() (results []*model.ConfigLink, err error) {
	err = obj.DB.WithContext(obj.ctx).Model(model.ConfigLink{}).Find(&results).Error

	return
}

func (obj *_ConfigLinkMgr) Count(count *int64) (tx *gorm.DB) {
	return obj.DB.WithContext(obj.ctx).Model(model.ConfigLink{}).Count(count)
}

// WithID id获取
func (obj *_ConfigLinkMgr) WithID(id int) Option {
	return optionFunc(func(o *options) { o.query["id"] = id })
}

// WithConfigID config_id获取
func (obj *_ConfigLinkMgr) WithConfigID(configID int) Option {
	return optionFunc(func(o *options) { o.query["config_id"] = configID })
}

// WithPublicConfigID public_config_id获取
func (obj *_ConfigLinkMgr) WithPublicConfigID(publicConfigID int) Option {
	return optionFunc(func(o *options) { o.query["public_config_id"] = publicConfigID })
}

// GetFromID 通过id获取内容
func (obj *_ConfigLinkMgr) GetFromID(id int) (result model.ConfigLink, err error) {
	err = obj.DB.WithContext(obj.ctx).Model(model.ConfigLink{}).Where("`id` = ?", id).Find(&result).Error

	return
}

// GetBatchFromID 批量查找
func (obj *_ConfigLinkMgr) GetBatchFromID(ids []int) (results []*model.ConfigLink, err error) {
	err = obj.DB.WithContext(obj.ctx).Model(model.ConfigLink{}).Where("`id` IN (?)", ids).Find(&results).Error

	return
}

// GetFromConfigID 通过config_id获取内容
func (obj *_ConfigLinkMgr) GetFromConfigID(configID int) (results []*model.ConfigLink, err error) {
	err = obj.DB.WithContext(obj.ctx).Model(model.ConfigLink{}).Where("`config_id` = ?", configID).Find(&results).Error

	return
}

// GetBatchFromConfigID 批量查找
func (obj *_ConfigLinkMgr) GetBatchFromConfigID(configIDs []int) (results []*model.ConfigLink, err error) {
	err = obj.DB.WithContext(obj.ctx).Model(model.ConfigLink{}).Where("`config_id` IN (?)", configIDs).Find(&results).Error

	return
}

// GetFromPublicConfigID 通过public_config_id获取内容
func (obj *_ConfigLinkMgr) GetFromPublicConfigID(publicConfigID int) (results []*model.ConfigLink, err error) {
	err = obj.DB.WithContext(obj.ctx).Model(model.ConfigLink{}).Where("`public_config_id` = ?", publicConfigID).Find(&results).Error

	return
}

// GetBatchFromPublicConfigID 批量查找
func (obj *_ConfigLinkMgr) GetBatchFromPublicConfigID(publicConfigIDs []int) (results []*model.ConfigLink, err error) {
	err = obj.DB.WithContext(obj.ctx).Model(model.ConfigLink{}).Where("`public_config_id` IN (?)", publicConfigIDs).Find(&results).Error

	return
}

func (obj *_ConfigLinkMgr) CreateConfigLink(bean *model.ConfigLink) (err error) {
	err = obj.DB.WithContext(obj.ctx).Model(model.ConfigLink{}).Create(bean).Error

	return
}

func (obj *_ConfigLinkMgr) UpdateConfigLink(bean *model.ConfigLink) (err error) {
	err = obj.DB.WithContext(obj.ctx).Model(bean).Updates(bean).Error

	return
}

func (obj *_ConfigLinkMgr) DeleteConfigLink(bean *model.ConfigLink) (err error) {
	err = obj.DB.WithContext(obj.ctx).Model(model.ConfigLink{}).Delete(bean).Error

	return
}
