package repo

import (
	"context"
	"fmt"
	"time"

	"gorm.io/gorm"

	"github.com/HYY-yu/sail/internal/service/sail/model"
)

// Code generated by gormt. DO NOT EDIT.

type _ProjectGroupMgr struct {
	*_BaseMgr
}

// ProjectGroupMgr open func
func ProjectGroupMgr(db *gorm.DB) *_ProjectGroupMgr {
	if db == nil {
		panic(fmt.Errorf("ProjectGroupMgr need init by db"))
	}
	ctx, cancel := context.WithCancel(context.Background())
	return &_ProjectGroupMgr{_BaseMgr: &_BaseMgr{DB: db.Table("project_group"), isRelated: globalIsRelated, ctx: ctx, cancel: cancel, timeout: -1}}
}

// WithContext set context to db
func (obj *_ProjectGroupMgr) WithContext(c context.Context) *_ProjectGroupMgr {
	if c != nil {
		obj.ctx = c
	}
	return obj
}

func (obj *_ProjectGroupMgr) WithSelects(idName string, selects ...string) *_ProjectGroupMgr {
	if len(selects) > 0 {
		if len(idName) > 0 {
			selects = append(selects, idName)
		}
		// 对Select进行去重
		selectMap := make(map[string]int, len(selects))
		for _, e := range selects {
			if _, ok := selectMap[e]; !ok {
				selectMap[e] = 1
			}
		}

		newSelects := make([]string, 0, len(selects))
		for k := range selectMap {
			if len(k) > 0 {
				newSelects = append(newSelects, k)
			}
		}
		obj.DB = obj.DB.Select(newSelects)
	}
	return obj
}

func (obj *_ProjectGroupMgr) WithOmit(omit ...string) *_ProjectGroupMgr {
	if len(omit) > 0 {
		obj.DB = obj.DB.Omit(omit...)
	}
	return obj
}

func (obj *_ProjectGroupMgr) WithOptions(opts ...Option) *_ProjectGroupMgr {
	options := options{
		query: make(map[string]interface{}, len(opts)),
	}
	for _, o := range opts {
		o.apply(&options)
	}
	obj.DB = obj.DB.Where(options.query)
	return obj
}

// GetTableName get sql table name.获取数据库名字
func (obj *_ProjectGroupMgr) GetTableName() string {
	return "project_group"
}

// Reset 重置gorm会话
func (obj *_ProjectGroupMgr) Reset() *_ProjectGroupMgr {
	obj.new()
	return obj
}

// Get 获取
func (obj *_ProjectGroupMgr) Get() (result model.ProjectGroup, err error) {
	err = obj.DB.WithContext(obj.ctx).Model(model.ProjectGroup{}).Find(&result).Error

	return
}

// Gets 获取批量结果
func (obj *_ProjectGroupMgr) Gets() (results []*model.ProjectGroup, err error) {
	err = obj.DB.WithContext(obj.ctx).Model(model.ProjectGroup{}).Find(&results).Error

	return
}

func (obj *_ProjectGroupMgr) Count(count *int64) (tx *gorm.DB) {
	return obj.DB.WithContext(obj.ctx).Model(model.ProjectGroup{}).Count(count)
}

// WithID id获取
func (obj *_ProjectGroupMgr) WithID(id int) Option {
	return optionFunc(func(o *options) { o.query["id"] = id })
}

// WithName name获取
func (obj *_ProjectGroupMgr) WithName(name string) Option {
	return optionFunc(func(o *options) { o.query["name"] = name })
}

// WithCreateTime create_time获取
func (obj *_ProjectGroupMgr) WithCreateTime(createTime time.Time) Option {
	return optionFunc(func(o *options) { o.query["create_time"] = createTime })
}

// WithCreateBy create_by获取
func (obj *_ProjectGroupMgr) WithCreateBy(createBy int) Option {
	return optionFunc(func(o *options) { o.query["create_by"] = createBy })
}

// WithDeleteTime delete_time获取
func (obj *_ProjectGroupMgr) WithDeleteTime(deleteTime int) Option {
	return optionFunc(func(o *options) { o.query["delete_time"] = deleteTime })
}

// GetFromID 通过id获取内容
func (obj *_ProjectGroupMgr) GetFromID(id int) (result model.ProjectGroup, err error) {
	err = obj.DB.WithContext(obj.ctx).Model(model.ProjectGroup{}).Where("`id` = ?", id).Find(&result).Error

	return
}

// GetBatchFromID 批量查找
func (obj *_ProjectGroupMgr) GetBatchFromID(ids []int) (results []*model.ProjectGroup, err error) {
	err = obj.DB.WithContext(obj.ctx).Model(model.ProjectGroup{}).Where("`id` IN (?)", ids).Find(&results).Error

	return
}

// GetFromName 通过name获取内容
func (obj *_ProjectGroupMgr) GetFromName(name string) (results []*model.ProjectGroup, err error) {
	err = obj.DB.WithContext(obj.ctx).Model(model.ProjectGroup{}).Where("`name` = ?", name).Find(&results).Error

	return
}

// GetBatchFromName 批量查找
func (obj *_ProjectGroupMgr) GetBatchFromName(names []string) (results []*model.ProjectGroup, err error) {
	err = obj.DB.WithContext(obj.ctx).Model(model.ProjectGroup{}).Where("`name` IN (?)", names).Find(&results).Error

	return
}

// GetFromCreateTime 通过create_time获取内容
func (obj *_ProjectGroupMgr) GetFromCreateTime(createTime time.Time) (results []*model.ProjectGroup, err error) {
	err = obj.DB.WithContext(obj.ctx).Model(model.ProjectGroup{}).Where("`create_time` = ?", createTime).Find(&results).Error

	return
}

// GetBatchFromCreateTime 批量查找
func (obj *_ProjectGroupMgr) GetBatchFromCreateTime(createTimes []time.Time) (results []*model.ProjectGroup, err error) {
	err = obj.DB.WithContext(obj.ctx).Model(model.ProjectGroup{}).Where("`create_time` IN (?)", createTimes).Find(&results).Error

	return
}

// GetFromCreateBy 通过create_by获取内容
func (obj *_ProjectGroupMgr) GetFromCreateBy(createBy int) (results []*model.ProjectGroup, err error) {
	err = obj.DB.WithContext(obj.ctx).Model(model.ProjectGroup{}).Where("`create_by` = ?", createBy).Find(&results).Error

	return
}

// GetBatchFromCreateBy 批量查找
func (obj *_ProjectGroupMgr) GetBatchFromCreateBy(createBys []int) (results []*model.ProjectGroup, err error) {
	err = obj.DB.WithContext(obj.ctx).Model(model.ProjectGroup{}).Where("`create_by` IN (?)", createBys).Find(&results).Error

	return
}

// GetFromDeleteTime 通过delete_time获取内容
func (obj *_ProjectGroupMgr) GetFromDeleteTime(deleteTime int) (results []*model.ProjectGroup, err error) {
	err = obj.DB.WithContext(obj.ctx).Model(model.ProjectGroup{}).Where("`delete_time` = ?", deleteTime).Find(&results).Error

	return
}

// GetBatchFromDeleteTime 批量查找
func (obj *_ProjectGroupMgr) GetBatchFromDeleteTime(deleteTimes []int) (results []*model.ProjectGroup, err error) {
	err = obj.DB.WithContext(obj.ctx).Model(model.ProjectGroup{}).Where("`delete_time` IN (?)", deleteTimes).Find(&results).Error

	return
}

func (obj *_ProjectGroupMgr) CreateProjectGroup(bean *model.ProjectGroup) (err error) {
	err = obj.DB.WithContext(obj.ctx).Model(model.ProjectGroup{}).Create(bean).Error

	return
}

func (obj *_ProjectGroupMgr) UpdateProjectGroup(bean *model.ProjectGroup) (err error) {
	err = obj.DB.WithContext(obj.ctx).Model(bean).Updates(bean).Error

	return
}

func (obj *_ProjectGroupMgr) DeleteProjectGroup(bean *model.ProjectGroup) (err error) {
	err = obj.DB.WithContext(obj.ctx).Model(model.ProjectGroup{}).Delete(bean).Error

	return
}
