package repo

import (
	"context"
	"fmt"
	"time"

	"gorm.io/gorm"

	"github.com/HYY-yu/sail/internal/service/sail/model"
)

// Code generated by gormt. DO NOT EDIT.

type _NamespaceMgr struct {
	*_BaseMgr
}

// NamespaceMgr open func
func NamespaceMgr(ctx context.Context, db *gorm.DB) *_NamespaceMgr {
	if db == nil {
		panic(fmt.Errorf("NamespaceMgr need init by db"))
	}
	ctx, cancel := context.WithCancel(ctx)
	return &_NamespaceMgr{_BaseMgr: &_BaseMgr{DB: db.Table("namespace"), isRelated: globalIsRelated, ctx: ctx, cancel: cancel, timeout: -1}}
}

func (obj *_NamespaceMgr) WithSelects(idName string, selects ...string) *_NamespaceMgr {
	if len(selects) > 0 {
		if len(idName) > 0 {
			selects = append(selects, idName)
		}
		// 对Select进行去重
		selectMap := make(map[string]int, len(selects))
		for _, e := range selects {
			if _, ok := selectMap[e]; !ok {
				selectMap[e] = 1
			}
		}

		newSelects := make([]string, 0, len(selects))
		for k := range selectMap {
			if len(k) > 0 {
				newSelects = append(newSelects, k)
			}
		}
		obj.DB = obj.DB.Select(newSelects)
	}
	return obj
}

func (obj *_NamespaceMgr) WithOmit(omit ...string) *_NamespaceMgr {
	if len(omit) > 0 {
		obj.DB = obj.DB.Omit(omit...)
	}
	return obj
}

func (obj *_NamespaceMgr) WithOptions(opts ...Option) *_NamespaceMgr {
	options := options{
		query: make(map[string]queryData, len(opts)),
	}
	for _, o := range opts {
		o.apply(&options)
	}
	for k, v := range options.query {
		obj.DB = obj.DB.Where(k+" "+v.cond, v.data)
	}
	return obj
}

// GetTableName get sql table name.获取数据库名字
func (obj *_NamespaceMgr) GetTableName() string {
	return "namespace"
}

// Reset 重置gorm会话
func (obj *_NamespaceMgr) Reset() *_NamespaceMgr {
	obj.new()
	return obj
}

// Get 获取
func (obj *_NamespaceMgr) Get() (result model.Namespace, err error) {
	err = obj.DB.WithContext(obj.ctx).Model(model.Namespace{}).Find(&result).Error

	return
}

// Gets 获取批量结果
func (obj *_NamespaceMgr) Gets() (results []*model.Namespace, err error) {
	err = obj.DB.WithContext(obj.ctx).Model(model.Namespace{}).Find(&results).Error

	return
}

func (obj *_NamespaceMgr) Count(count *int64) (tx *gorm.DB) {
	return obj.DB.WithContext(obj.ctx).Model(model.Namespace{}).Count(count)
}

func (obj *_NamespaceMgr) HasRecord() (bool, error) {
	var count int64
	err := obj.DB.WithContext(obj.ctx).Model(model.Namespace{}).Count(&count).Error
	if err != nil {
		return false, err
	}
	return count != 0, nil
}

// WithID id获取
func (obj *_NamespaceMgr) WithID(id int, cond ...string) Option {
	return optionFunc(func(o *options) {
		if len(cond) == 0 {
			cond = []string{" = ? "}
		}
		o.query["id"] = queryData{
			cond: cond[0],
			data: id,
		}
	})
}

// WithProjectGroupID project_group_id获取
func (obj *_NamespaceMgr) WithProjectGroupID(projectGroupID int, cond ...string) Option {
	return optionFunc(func(o *options) {
		if len(cond) == 0 {
			cond = []string{" = ? "}
		}
		o.query["project_group_id"] = queryData{
			cond: cond[0],
			data: projectGroupID,
		}
	})
}

// WithName name获取
func (obj *_NamespaceMgr) WithName(name string, cond ...string) Option {
	return optionFunc(func(o *options) {
		if len(cond) == 0 {
			cond = []string{" = ? "}
		}
		o.query["name"] = queryData{
			cond: cond[0],
			data: name,
		}
	})
}

// WithRealTime real_time获取 是否是实时发布
func (obj *_NamespaceMgr) WithRealTime(realTime bool, cond ...string) Option {
	return optionFunc(func(o *options) {
		if len(cond) == 0 {
			cond = []string{" = ? "}
		}
		o.query["real_time"] = queryData{
			cond: cond[0],
			data: realTime,
		}
	})
}

// WithCreateTime create_time获取
func (obj *_NamespaceMgr) WithCreateTime(createTime time.Time, cond ...string) Option {
	return optionFunc(func(o *options) {
		if len(cond) == 0 {
			cond = []string{" = ? "}
		}
		o.query["create_time"] = queryData{
			cond: cond[0],
			data: createTime,
		}
	})
}

// WithCreateBy create_by获取
func (obj *_NamespaceMgr) WithCreateBy(createBy int, cond ...string) Option {
	return optionFunc(func(o *options) {
		if len(cond) == 0 {
			cond = []string{" = ? "}
		}
		o.query["create_by"] = queryData{
			cond: cond[0],
			data: createBy,
		}
	})
}

// WithDeleteTime delete_time获取
func (obj *_NamespaceMgr) WithDeleteTime(deleteTime int, cond ...string) Option {
	return optionFunc(func(o *options) {
		if len(cond) == 0 {
			cond = []string{" = ? "}
		}
		o.query["delete_time"] = queryData{
			cond: cond[0],
			data: deleteTime,
		}
	})
}

func (obj *_NamespaceMgr) CreateNamespace(bean *model.Namespace) (err error) {
	err = obj.DB.WithContext(obj.ctx).Model(model.Namespace{}).Create(bean).Error

	return
}

func (obj *_NamespaceMgr) UpdateNamespace(bean *model.Namespace) (err error) {
	err = obj.DB.WithContext(obj.ctx).Model(bean).Updates(bean).Error

	return
}

func (obj *_NamespaceMgr) DeleteNamespace(bean *model.Namespace) (err error) {
	err = obj.DB.WithContext(obj.ctx).Model(model.Namespace{}).Delete(bean).Error

	return
}
